version: "3.7"

services:
  tomcat:
    image: tomcat:8.5-jre8
    ports:
      - "8889:8080"
    depends_on:
      - postgres
    volumes:
      - "./build/libs/axelor-erp-6.5.3.war:/usr/local/tomcat/webapps/ROOT.war"
  postgres:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
